services:
  - type: web
    name: your-django-app
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn your_project.wsgi:application